### ISSUE TITLE
which checkpoint should i write?minigpt4?audio.pth or visual.pth?

### ISSUE THREAD

**Issue by DeerEyre** [DAMO-NLP-SG/Video-LLaMA#24]
if i want to use the demo?
what should i write in /video_llama_eval_withaudio.yaml
ckpt:?
ckpt_2?

**Comment by hangzhang-nlp** [comment]
![image](https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/21003563/aeaa9b87-dab9-4eca-a043-cd0e8257935c)

**Comment by DeerEyre** [comment]
should i fill this ckpt with pretrained_ckpt or finetune_ckpt?
i fill this two blank with. finetune-ziya13b-zh.pth and  finetune_vicuna7b_audiobranch.pth
my eval_config.yaml  is following:
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  llama_model: "vicuna-13b/" 
  imagebind_ckpt_path: "imagebind/"

  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"

  ckpt: "pretrain_vicuna7b_audiobranch.pth"
  ckpt_2: "finetune_vicuna7b_audiobranch.pth"


datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain
  
  
  but these get the wrong of 
  audio encoder initialized.
Load first Checkpoint: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Video_model/Video_LLaMa/pretrained_finetuned_weights/finetune-ziya13b-zh.pth
Traceback (most recent call last):
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/ganshu01/projects/Video-LLaMA-main/demo_audiovideo.py", line 66, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/ganshu01/projects/Video-LLaMA-main/video_llama/models/video_llama.py", line 598, in from_config
    ckpt = torch.load(ckpt_path, map_location="cpu")
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/ganshu01/envs/llama-ganshu/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/ganshu01/envs/llama-ganshu/lib/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

**Comment by DeerEyre** [comment]
**should i fill this ckpt with pretrained_ckpt or finetune_ckpt?
i fill this two blank with. finetune-ziya13b-zh.pth and finetune_vicuna7b_audiobranch.pth
my eval_config.yaml is following:**
model:
arch: video_llama
model_type: pretrain_vicuna
freeze_vit: True
freeze_qformer: True
max_txt_len: 512
end_sym: "###"
low_resource: False

frozen_llama_proj: False

llama_model: "vicuna-13b/"
imagebind_ckpt_path: "imagebind/"

fusion_head_layers: 2
max_frame_pos: 32
fusion_header_type: "seqTransf"

ckpt: "finetune-ziya13b-zh.pth"
ckpt_2: "finetune_vicuna7b_audiobranch.pth"

datasets:
webvid:
vis_processor:
train:
name: "alpro_video_eval"
n_frms: 8
image_size: 224
text_processor:
train:
name: "blip_caption"

run:
task: video_text_pretrain

**but these get the wrong of
audio encoder initialized.
Load first Checkpoint: /mnt/dolphinfs**/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Video_model/Video_LLaMa/pretrained_finetuned_weights/finetune-ziya13b-zh.pth
Traceback (most recent call last):
File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/ganshu01/projects/Video-LLaMA-main/demo_audiovideo.py", line 66, in
model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/ganshu01/projects/Video-LLaMA-main/video_llama/models/video_llama.py", line 598, in from_config
ckpt = torch.load(ckpt_path, map_location="cpu")
File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/ganshu01/envs/llama-ganshu/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
with _open_zipfile_reader(opened_file) as opened_zipfile:
File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/ganshu01/envs/llama-ganshu/lib/python3.9/site-packages/torch/serialization.py", line 283, in init
super().init(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

**Comment by shinever22** [comment]
Hi~We are researching a project, and the Webvid-2.5M dataset is very important to us. We found that the link is no longer working. Could you share this dataset with us?
shinever2022@gmail.com
