### ISSUE TITLE
video_llama_eval_withaudio.yaml   issue

### ISSUE THREAD

**Issue by imfurkaann** [DAMO-NLP-SG/Video-LLaMA#31]
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Traceback (most recent call last):
  File "/home/akilliceviribilisim/Video-LLaMA/venv/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/akilliceviribilisim/Video-LLaMA/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/pretrain_vicuna7b-v2.pth/resolve/main/tokenizer.model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/akilliceviribilisim/Video-LLaMA/venv/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/akilliceviribilisim/Video-LLaMA/venv/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/akilliceviribilisim/Video-LLaMA/venv/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1166, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/akilliceviribilisim/Video-LLaMA/venv/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)

Traceback (most recent call last):
  File "demo_audiovideo.py", line 66, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/home/akilliceviribilisim/Video-LLaMA/video_llama/models/video_llama.py", line 567, in from_config
    model = cls(
  File "/home/akilliceviribilisim/Video-LLaMA/video_llama/models/video_llama.py", line 120, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)
  File "/home/akilliceviribilisim/Video-LLaMA/venv/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1770, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/home/akilliceviribilisim/Video-LLaMA/venv/lib/python3.8/site-packages/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: pretrain_vicuna7b-v2.pth is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True
`.

can you help me how can i solve it

**Comment by lixin4ever** [comment]
@imfurkaann Sorry for the late reply. It seems that you incorrectly set the value of`llama_model` as "pretrain_vicuna7b-v2.pth". `llama_model` is the variable storing the path to pre-trained vicuna weights while "pretrain_vicuna7b-v2.pth" is the checkpoint for the learnable parameters (i.e., Video Q-former & a position embedding layer & a linear layer) between the visual encoder and vicuna-7b.
