### ISSUE TITLE
AssertionError: Unknown model type llama_v2

### ISSUE THREAD

**Issue by alvaro-budria** [DAMO-NLP-SG/Video-LLaMA#65]
I am trying the `demo_video.py` with LLAMA2 weights. I downloaded the VL encoder and the LLAMA weights from [the Video-LLAMA 2 HF repo](https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-7B-Finetuned/tree/main).

I modified the following fields in `eval_configs/video_llama_eval_only_vl.yaml`:

```
model_type: llama_v2  # pretrain_vicuna
low_resource: True
llama_model: "Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/"
 ckpt: "Video-LLaMA-2-7B-Finetuned/VL_LLaMA_2_7B_Finetuned.pth"  # you can use our pretrained ckpt from https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Pretrained/
 equip_audio_branch: False
```

Then I run `python demo_video.py --cfg-path eval_configs/video_llama_eval_only_vl.yaml --gpu-id 5`, and I get this error message:

```
/home/abudria/miniconda3/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in 0.14. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/home/abudria/miniconda3/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:25: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in 0.14. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
Initializing Chat
Traceback (most recent call last):
  File "/home/abudria/GV_LL/demo_video.py", line 62, in <module>
    cfg = Config(args)
  File "/home/abudria/GV_LL/video_llama/common/config.py", line 30, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/home/abudria/GV_LL/video_llama/common/config.py", line 71, in build_model_config
    model_config_path = model_cls.default_config_path(model_type=model_type)
  File "/home/abudria/GV_LL/video_llama/models/base_model.py", line 77, in default_config_path
    assert (
AssertionError: Unknown model type llama_v2
```

Is this a bug or am I forgetting something?

**Comment by hangzhang-nlp** [comment]
In  `eval_configs/video_llama_eval_only_vl.yaml `,  `model_type `  does not need to change.
You should run   `python demo_video.py --cfg-path eval_configs/video_llama_eval_only_vl.yaml --model_type llama_v2 --gpu-id 5 `
