### ISSUE TITLE
demo启动后报错，这个是什么原因嗯？

### ISSUE THREAD

**Issue by CaicaiJason** [DAMO-NLP-SG/Video-LLaMA#74]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='6jexvegyb39_2' coro=<Queue.process_events() done, defined at /data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 2, 'data': [...on_hash': '6jexvegyb39'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 2, 'data': [...on_hash': '6jexvegyb39'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing

**Comment by hangzhang-nlp** [comment]
可能是gradio的版本导致的吧，没遇见过

**Comment by CaicaiJason** [comment]
你那边正常运行的gradio是什么版本》

**Comment by Givyuscss** [comment]
更新gradio到最新版本，别用requirement里的3.24.1
